<?php
// update_prices.php - Updates unit prices for all inventory items. Delete after running!

$branches = [
    'Agbajeena' => [
        'host' => getenv('DB_Agbajeena_HOST'),
        'dbname' => getenv('DB_Agbjeena_NAME'),
        'user' => getenv('DB_Agbajeena_USER'),
        'pass' => getenv('DB_Agbajeena_PASS'),
    ],
    'Olebu' => [
        'host' => getenv('DB_Olebu_HOST'),
        'dbname' => getenv('DB_Olebu_NAME'),
        'user' => getenv('DB_Olebu_USER'),
        'pass' => getenv('DB_Olebu_PASS'),
    ],
];

echo "<h2>Inventory Price Update</h2>";
foreach (\$branches as \$branchName => \$cfg) {
    echo "<h3>Branch: $branchName</h3>";
    try {
        \$pdo = new PDO(
            "mysql:host={\$cfg['host']};dbname={\$cfg['dbname']};charset=utf8",
            \$cfg['user'], \$cfg['pass'],
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        \$count = 0;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['TINATETT VENECARE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 65.00 WHERE `item` = ?")->execute(['HI LADY VIRGIN MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['ADUTWUMWAA BITTERS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 97.00 WHERE `item` = ?")->execute(['GYNICARE SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['MADAM CATHERINE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['GROFYN HERBAL TONIC'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['VIKIL 20'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['IMBOOST HERBAL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ZAHARA HERBAL MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['GIFAS MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ALAPHOID'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['AMUZU PEE MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['SOLAK MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['VICTORY GARLIC MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['3P GARLIC MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['AMUZU GARLIC BIITTERS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 47.00 WHERE `item` = ?")->execute(['LIVING BITTERS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['AGBEVE TONIC'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['HAC-CER MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['HAC-CER CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 36.00 WHERE `item` = ?")->execute(['GASTO MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ZAHARA GEE CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['TAABEA HERBAL MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['MASADA MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 42.00 WHERE `item` = ?")->execute(['ROOTER MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['MAMPONG ENTERICA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['NAZO'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['DR COTE D`IVIORE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['SOLDIER BALM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['JOY OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['BOAFUO OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['MAAME DAGOMBA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ROBB OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ERNEST OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['GANA BALM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['SHIKRO OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['EKURO BEWU'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ABONIKI'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['ESSENTIAL EMBROICATION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['KONGO OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['ZINTAB 10 MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['MR .Q'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 230.00 WHERE `item` = ?")->execute(['WELLWOMAN ORIGINAL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 46.00 WHERE `item` = ?")->execute(['HI LADY FEMININE WASH'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['MEDISOFT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['ALPHA GARLIC CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['SIBI MEN CAPS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['SIBI WOMEN CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['VALUPAkK COD LIVER CAPS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 24.00 WHERE `item` = ?")->execute(['ADOM KOO OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 75.00 WHERE `item` = ?")->execute(['GIVERS P CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['LAWSON DELAYMAN CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 24.00 WHERE `item` = ?")->execute(['ADOM KOO OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['ADOM KOO MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['CALAMINE LOTION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['GV PAINT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['SPIRIT S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['SPIRIT B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['TOUCH AND GO'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['STOPKOF DRY COUGH MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['HONEYCOUGH COUGH MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['STOPKOF ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['LINCTUS ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['AMCOF ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['LETALIN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['KELCUF ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['.MENTHOX COUGH MIXTURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['FLEMEX ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['KOFOF ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['DIPHEX ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['KOFFEX ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['SAMALIN ADULT NON DROWSY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['SAMALIN ADULT PLAIN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 24.00 WHERE `item` = ?")->execute(['MALIN ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 43.00 WHERE `item` = ?")->execute(['VISCOF D'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 42.00 WHERE `item` = ?")->execute(['VISCOF S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 43.00 WHERE `item` = ?")->execute(['VISCOF PLAIN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['MUCOLEX ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 75.00 WHERE `item` = ?")->execute(['MENTHODEX ADULT S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 56.00 WHERE `item` = ?")->execute(['MENTHODEX ADULT B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['ZUBES EXPECTORANT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['ZUBES EXTRA STRONG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['HYDROGEN PEROXIDE ECL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['HYDROGEN PEROXIDE LOCAL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['MIST POT CIT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['MIST SENNACO'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['MMT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['MIST F.A.C'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['NANA AGYEI'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['DIAGELLATES S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 46.00 WHERE `item` = ?")->execute(['DIAGELLATES B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ALUSIL PLUS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['POLYGEL S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['POLYGEL B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['MAGACID SUSP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 38.00 WHERE `item` = ?")->execute(['GASTRONE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 42.00 WHERE `item` = ?")->execute(['GASTRONE PLUS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 64.00 WHERE `item` = ?")->execute(['NUGEL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 67.00 WHERE `item` = ?")->execute(['NUGEL O'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['ALUDROX G'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['MAGACID TABS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['HEPTOLIF TABS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['GML APETI TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['CYFEN TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 8.00 WHERE `item` = ?")->execute(['SUPA APETI TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['APETAMIN TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['LOPERAMIDE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['PEN V'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['BISACODYL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['MULTIVITE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['FOLIC ACID'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['BCO'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['CITRO C'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['ORS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['MARTINSS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['NO 10'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['OSTEOCARE TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['OSTEOCARE SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['BABYVITE SYRUP S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['BABYVITE SYRUP B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['KIDIVITE SYRUP S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['KIDIVITE SYRUP B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['GLUCOSE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['APETATRUST SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['CYFEN SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['GUDAPEST SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 39.00 WHERE `item` = ?")->execute(['GML APETI SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 37.00 WHERE `item` = ?")->execute(['HEPTOLIF SYRUP B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['HEPTOLIF SYRUP S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ABYVITA SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 27.00 WHERE `item` = ?")->execute(['LEENA SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 65.00 WHERE `item` = ?")->execute(['APETAMIN SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['ROBB INHALER'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['KLIRE INHALER'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['JET 2 INHALER'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['FOLIVITE SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['3FER SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['DUROL S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['DUROL B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['DEXORANGE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['FOLIGROW SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['FOLIGROW PLUS SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['CCORORANGE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['HAEMOFORTE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['BECOATIN SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['BX SYRUP S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 27.00 WHERE `item` = ?")->execute(['BX SYRUP B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['VIGORIX FORTE SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['VIGORIX FORTE CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['ABYVITA CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ABYVITA SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 39.00 WHERE `item` = ?")->execute(['JARIFAN 2 SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ESKARON SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 54.00 WHERE `item` = ?")->execute(['HAEM UP SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['FERROFIX SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['NEXCOFER SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 38.00 WHERE `item` = ?")->execute(['NEOFERON SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 67.00 WHERE `item` = ?")->execute(['ZINCOFER SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['VIROL SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 115.00 WHERE `item` = ?")->execute(['FEROGLOBIN SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 42.00 WHERE `item` = ?")->execute(['CITY BLOOD TONIC'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['LUMETRUST SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['MALAR 2 SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['CARTEF SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['LUFART SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['LONART SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['QUININE SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ARFAN SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 24.00 WHERE `item` = ?")->execute(['GOLDY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['CALCIUM B12 SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 69.00 WHERE `item` = ?")->execute(['TRES-ORIX B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['TRES ORIX S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['CIROTAMIN SYUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['ZINCOVIT SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['ENERVII'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 125.00 WHERE `item` = ?")->execute(['CYPRODINE SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 125.00 WHERE `item` = ?")->execute(['CYPRODINE CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['ZINCOVIT CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['CORORANGE CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['FOLIGROW CAPS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['NEXCOFER CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['GACET 1G'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['GR PARA 500MG SUPP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.50 WHERE `item` = ?")->execute(['GACET 125 SUPP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.50 WHERE `item` = ?")->execute(['GACET 250 SUPP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['DICLOFENAC SUPP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['DOMI 30'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['DOMI 10'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['MALAR 2 TABS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['LUFART DS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['CARTEF 20 120 TABS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['LONART 20/120 TABS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['LUFART 20/120 TABS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['CARTEF DS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['VEGATEM TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['CENART FORTE TABS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['SHALARTEM TABS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ARFAN TABS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['POLYFER CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['POLYFER 150MLS SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 26.00 WHERE `item` = ?")->execute(['POLYER 200MLS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['MAGNAVITE CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['MAGNAVITE SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['SEPTRIN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['PARA LOCAL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['BRUFFEN SKYBRU'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['RONFIT FORTE CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['PELADOL EXTRA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['MALARIA TEST'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ESKYPAN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['LADINAS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['TYPHOID TEST'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['ZUBES LOZENGES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['PREGNANCY TEST'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['BECOATIN TABLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['CIROTAMIN TABLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['APETATRUST TABLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['GYPRONE PLUS TABLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['LEENA TABLETS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 53.00 WHERE `item` = ?")->execute(['MILK OF MAGNESIA B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['MILK OF MAAGNESIA S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 100.00 WHERE `item` = ?")->execute(['IMPRESSOR CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 95.00 WHERE `item` = ?")->execute(['IMPRESSOR OIL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['AMINO KLIRE SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ODYMIN SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['YOGIFER SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['BIOGLOBIN S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['BIOGLOBIN B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ESKARON CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['KOFOF FAMILY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['LETAPLEX B'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['AYTRONS MULTIVITAMINS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 112.00 WHERE `item` = ?")->execute(['FEROGLOBIN CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.50 WHERE `item` = ?")->execute(['PLASTER STRIP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 16.00 WHERE `item` = ?")->execute(['CETAPOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['PARAMED'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 16.00 WHERE `item` = ?")->execute(['E-PANOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['LETAMOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['SKY PARA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ENAFEN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['SKYBRU SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['EMGIPROFEN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['CHILDCARE LETAFEN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['RIDDLES PARACETAMOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['AMCOF JUNIOR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['AMCOF INFANT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['RIDDLES JUNIOR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['TEEDAR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['EFPAC JUNIOR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 16.00 WHERE `item` = ?")->execute(['ZUDREX SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['SALOCOLD SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['BASECOLD SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['COLDRILIF SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 38.00 WHERE `item` = ?")->execute(['CONGESTYL SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['PROCOLD SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 21.00 WHERE `item` = ?")->execute(['FLEMEX SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['MENTHOX JUNIOR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ZUBES JUNIOR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['STOPKOF JUNIOR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['STOPKOF INFANT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['MALIN JUNIOR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['MALIN BABY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['KOFOF BABY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['KOFFEX JUNIOR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['SAMALIN JUNIOR PLAIN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['SAMALIN JUNIOR NON DROWSY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['LUEX CHESTY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['LUEX BABY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['MUCOLEX JUNIOR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['BELLS PARACETAMOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['KOFOF CHILD'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['SALBUTALIN SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['SEVEN SEAS COD LIVER OIL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 112.00 WHERE `item` = ?")->execute(['CALPOL 2+ SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['BELS COD LIVER OIL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['CETRIZAN SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['HISTAZINE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['PROMETHAZINE SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['PROMECINE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ASCORYL PLUS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['ASCORYL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['BELL’S VIT C'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['LETAVIT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['CHILDCARE ASCORBIN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['LABFLU'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 26.00 WHERE `item` = ?")->execute(['ANTIE MARY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['BONNISAN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['SALO-C'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ESKADOL NITE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['CONGESTYL TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ZUDREX TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['SALOCOLD TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['RONFIT COLD TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['FLUREST'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['SAMALIN LOZENGES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['MALIN LOZENGES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['LEXOFEN CAPLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ASNAC 75'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ASNAC 100'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['LOFNAC/DICNAC 100 TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['APC'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ZULU 100'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 14.00 WHERE `item` = ?")->execute(['ZULU MR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ZULU EXTRA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['GOFEX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['BRUPREX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['NAKLOFEN DUO'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['BRUFFEN UK'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['PAINGAY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['FENBASE EXTRA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['DIPEX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['DOLO PLUS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['DOLO TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ZULU PLUS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['GEBEDOL PLUS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['GEBEDOL EXTRA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['GEBEDOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['GEBEDOL FORTE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['PARAFENAC'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['PARAFENAC EXTRA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['COLDRILIF CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['PROCOLD TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['CETRIZAN TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['IBUCAP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 26.00 WHERE `item` = ?")->execute(['FISHERMAN’S FRIEND'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['BABYVITE DROPS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['CORORANGE DROPS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ZINCOVITE DROPS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['KIDIVITE DROPS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['VALUPAK COD LIVER OIL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['VITAMIN BCO POROSURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['VITAMIN BCO ACCORD'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 48.00 WHERE `item` = ?")->execute(['FOLIC ACID 90’S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['FOLIC ACID 30’S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['FOLIC ACID 28’S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 37.00 WHERE `item` = ?")->execute(['VITAFOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['KOJACK P'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['KOJACK F'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['CHOCHO CREAM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['RONFIT OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['EPIDERM B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['EPIDERM S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 37.00 WHERE `item` = ?")->execute(['SURFAZ'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['DIPROSON CREAM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['CANDIDERM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['TETRACYCLINE OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['MYCOLEX CREAM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['MYCOLEX 3 CREAM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['ESKYZOLE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['MERCY OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['FUNBACT A B/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['FUNBACT A S/S'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['KETAZOLE CREAM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['PEN V OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['BADRUFF'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['DERMIRON PLUS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['LAVINA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 24.00 WHERE `item` = ?")->execute(['MAJOR NASAL DROP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['SANA NASAL DROP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['CHLOR EAR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['GENTA K'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['RAMICOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['EXEVIN ADULT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['OLIVE OIL EAR DROP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 27.00 WHERE `item` = ?")->execute(['SECLEAR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['CIPROLEX EAR/EYE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 95.00 WHERE `item` = ?")->execute(['PILEX TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['PILEX OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['OMEGA OIL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['DREZ POWDER'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['DREZ SOLUTION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['DREZ OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['DEXONE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['COMBACT A'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['BELLS OLIVE OIL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['MERCY SOAP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['CHOCHO SOAP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['CHLORAMPHENICOL OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['BORGES OLIVE OIL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 56.00 WHERE `item` = ?")->execute(['NEO-HYCOLEX EAR/EYES/NOSE DROP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 49.00 WHERE `item` = ?")->execute(['DEEP HEAT OINTMENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['KWICK ACTION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['PAIN OFF'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['DYNEWELL TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['CHLORAMPHENICOL CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['LETACAM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['RAPINOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['YODI'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['AMPICILLIN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['FLAGYL TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['AMOXYL CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['LETAVIN 125'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['LETAVIN 500'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['TETRACYCLINE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['SKYCID OMEPRAZOLE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['ASMANOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['ASMADRIN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['RHIZIN TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['M AND B 760'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['FLUCLOXACILLIN CAPSULES 250MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['DOXYCYCLINE CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['SALBUTAMOL TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['FIESTA GEL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['FIESTA CONDOM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['LEVON 2 GEL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['INDOCID'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['AMCICLOX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['STREPTOL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 70.00 WHERE `item` = ?")->execute(['VERMOX SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 47.00 WHERE `item` = ?")->execute(['ZENTEL SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 130.00 WHERE `item` = ?")->execute(['M2 TONE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['WORMPLEX TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['WORMPLEX SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 8.00 WHERE `item` = ?")->execute(['TANZOL SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['NESBEN SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['LETAMOX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['VERMOX TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['TRUSTZOLE SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['TRUSTZOLE TABLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['TANZOL TABLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['WORMPLEX TABLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['ZENTEL TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['NESBEN TABLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['DUREX FEATHER'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['DUREX FEELS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['DUREX EXTRA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['CONTRA 72'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['LEVON 2'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['LYDIA POSTPILL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['LYDIA DAILY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['FLUCONAZOLE VEGA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['STAGYL TABLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['FLUCONAZOLE TEVA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['MYCOSTAT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['SECURE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['VAGINAX 100'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['KLOVINAL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['CANALEX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 65.00 WHERE `item` = ?")->execute(['GYNO MYCOLEX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 54.00 WHERE `item` = ?")->execute(['DRAGON SPRAY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 70.00 WHERE `item` = ?")->execute(['IMAX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['KISS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['EBONY ORIGINAL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['EBONY PLUS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['REDSUN CAPSULES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['REDSUN JELLY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['DRAGON LOZENGES'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['DRAGON TABLET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['BASEBOOM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['KISS JELLY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['FLAMES CONDOM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['GOLD CIRCLE CONDOM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['BK-1'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['AMLODIPINE 10MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['AMLODIPINE 5MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 14.00 WHERE `item` = ?")->execute(['LOSARTAN 50 MG TEVA PER STRIP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 14.00 WHERE `item` = ?")->execute(['LOSARTAN 100M TEVA PER STRIP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['LOSARTAN 50 MG CRESCENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 11.00 WHERE `item` = ?")->execute(['LOSARTAN 100 MG CRESCENT'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['O-FORMIN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['NIFECARD XL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['NIFEMED XL'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['ATORVASTATIN 20 MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['ATORVASTATIN 40 MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 8.00 WHERE `item` = ?")->execute(['BENDRO 2.5MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 11.00 WHERE `item` = ?")->execute(['BENDRO 5MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['LISINOVA 10MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['NIFEDOSE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ENACIN- C'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['DACILLIN'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['ACYCLOVIR 200 MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 29.00 WHERE `item` = ?")->execute(['ACYCLOVIR 400MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['SKYCLAV 1G'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['SKYXLAV 625MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['GRMOX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['ZOLEXOV'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 31.00 WHERE `item` = ?")->execute(['LEOAB 500MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 70.00 WHERE `item` = ?")->execute(['CIPROLEX TZ'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['CIPROLEX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['AMOKSIKLAV 625MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['METRO F TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['ZYMAX TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 42.00 WHERE `item` = ?")->execute(['ENAFIX 200 TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['ENAFIX 200 SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 53.00 WHERE `item` = ?")->execute(['FOXITIL 500MG TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['OMEXET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['AZILEX SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['OXYNIC 457 SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['OXYNIC 228.5MG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['SKYCLAV457MG SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['FLAGYL 21’S TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['NOSPA'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['AMOKSIKLAV 457 SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 27.00 WHERE `item` = ?")->execute(['FLUXACIN SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['SOLUBLE VIT C'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['VITACARE PLUS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['AMOXICILLIN SUSPENSIONLUEX'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['AMOXICILLIN SUSP LETAP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['FLAGYL SUSPENSION LETAP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['X’ZOLE SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['METRO F SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['FUMET'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['CO-TRIMOXAZOLE LETAP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['CO-TRIMOXAZOLE MPG'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 27.00 WHERE `item` = ?")->execute(['SALO FULVIN SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['KEFFROX SUSPENSION'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['SHALCIP TZ'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['SHALCIP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['COMIT 50 TAB'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['COMIT 100 JELLY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['PREDNISOLONE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['GAUZE BANDAGE'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['CREPE BANDAGE 4’’'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['CREPE BANDAGE 6’’'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 8.00 WHERE `item` = ?")->execute(['CREPE BANDAGE 3’’'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['PLASTER ROLL 2’’'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['PLASTER ROLL 4’’'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['PLASTER ROLL 6’’'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['VALUPAK MULTIVITAMINS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['YOGIFER SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['ABYTONE SYR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 65.00 WHERE `item` = ?")->execute(['ODYYNE SYRUP'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 14.00 WHERE `item` = ?")->execute(['ZULU MR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 65.00 WHERE `item` = ?")->execute(['ODYNE CAPS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['RHIZIN SYR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['KLIRE TABLETS'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['CETAPOL PM'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['DIPHEX BABY'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['DIPHEX JUNIOR'])) \$count++;
        if (\$pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['KELCUF JNR'])) \$count++;
        echo "<p>✅ \$count items updated successfully.</p>";
    } catch (PDOException \$e) {
        echo "<p>❌ Error: " . htmlspecialchars(\$e->getMessage()) . "</p>";
    }
}
echo "<hr><p><strong>Done! Please delete this file now.</strong></p>";
?>