<?php
// update_prices.php - Delete after running!

$branches = [
    'Agbajeena' => [
        'host' => getenv('DB_Agbajeena_HOST'),
        'dbname' => getenv('DB_Agbjeena_NAME'),
        'user' => getenv('DB_Agbajeena_USER'),
        'pass' => getenv('DB_Agbajeena_PASS'),
    ],
    'Olebu' => [
        'host' => getenv('DB_Olebu_HOST'),
        'dbname' => getenv('DB_Olebu_NAME'),
        'user' => getenv('DB_Olebu_USER'),
        'pass' => getenv('DB_Olebu_PASS'),
    ],
];

echo "<h2>Inventory Price Update</h2>";
foreach ($branches as $branchName => $cfg) {
    echo "<h3>Branch: $branchName</h3>";
    try {
        $pdo = new PDO(
            "mysql:host={$cfg['host']};dbname={$cfg['dbname']};charset=utf8",
            $cfg['user'], $cfg['pass'],
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        $count = 0;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['TINATETT VENECARE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 65.00 WHERE `item` = ?")->execute(['HI LADY VIRGIN MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['ADUTWUMWAA BITTERS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 97.00 WHERE `item` = ?")->execute(['GYNICARE SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['MADAM CATHERINE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['GROFYN HERBAL TONIC']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['VIKIL 20']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['IMBOOST HERBAL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ZAHARA HERBAL MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['GIFAS MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ALAPHOID']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['AMUZU PEE MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['SOLAK MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['VICTORY GARLIC MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['3P GARLIC MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['AMUZU GARLIC BIITTERS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 47.00 WHERE `item` = ?")->execute(['LIVING BITTERS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['AGBEVE TONIC']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['HAC-CER MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['HAC-CER CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 36.00 WHERE `item` = ?")->execute(['GASTO MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ZAHARA GEE CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['TAABEA HERBAL MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['MASADA MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 42.00 WHERE `item` = ?")->execute(['ROOTER MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['MAMPONG ENTERICA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['NAZO']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['DR COTE D`IVIORE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['SOLDIER BALM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['JOY OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['BOAFUO OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['MAAME DAGOMBA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ROBB OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ERNEST OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['GANA BALM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['SHIKRO OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['EKURO BEWU']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ABONIKI']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['ESSENTIAL EMBROICATION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['KONGO OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['ZINTAB 10 MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['MR .Q']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 230.00 WHERE `item` = ?")->execute(['WELLWOMAN ORIGINAL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 46.00 WHERE `item` = ?")->execute(['HI LADY FEMININE WASH']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['MEDISOFT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['ALPHA GARLIC CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['SIBI MEN CAPS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['SIBI WOMEN CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['VALUPAkK COD LIVER CAPS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 24.00 WHERE `item` = ?")->execute(['ADOM KOO OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 75.00 WHERE `item` = ?")->execute(['GIVERS P CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['LAWSON DELAYMAN CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 24.00 WHERE `item` = ?")->execute(['ADOM KOO OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['ADOM KOO MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['CALAMINE LOTION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['GV PAINT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['SPIRIT S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['SPIRIT B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['TOUCH AND GO']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['STOPKOF DRY COUGH MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['HONEYCOUGH COUGH MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['STOPKOF ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['LINCTUS ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['AMCOF ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['LETALIN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['KELCUF ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['.MENTHOX COUGH MIXTURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['FLEMEX ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['KOFOF ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['DIPHEX ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['KOFFEX ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['SAMALIN ADULT NON DROWSY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['SAMALIN ADULT PLAIN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 24.00 WHERE `item` = ?")->execute(['MALIN ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 43.00 WHERE `item` = ?")->execute(['VISCOF D']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 42.00 WHERE `item` = ?")->execute(['VISCOF S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 43.00 WHERE `item` = ?")->execute(['VISCOF PLAIN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['MUCOLEX ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 75.00 WHERE `item` = ?")->execute(['MENTHODEX ADULT S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 56.00 WHERE `item` = ?")->execute(['MENTHODEX ADULT B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['ZUBES EXPECTORANT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['ZUBES EXTRA STRONG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['HYDROGEN PEROXIDE ECL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['HYDROGEN PEROXIDE LOCAL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['MIST POT CIT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['MIST SENNACO']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['MMT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['MIST F.A.C']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['NANA AGYEI']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['DIAGELLATES S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 46.00 WHERE `item` = ?")->execute(['DIAGELLATES B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ALUSIL PLUS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['POLYGEL S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['POLYGEL B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['MAGACID SUSP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 38.00 WHERE `item` = ?")->execute(['GASTRONE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 42.00 WHERE `item` = ?")->execute(['GASTRONE PLUS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 64.00 WHERE `item` = ?")->execute(['NUGEL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 67.00 WHERE `item` = ?")->execute(['NUGEL O']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['ALUDROX G']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['MAGACID TABS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['HEPTOLIF TABS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['GML APETI TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['CYFEN TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 8.00 WHERE `item` = ?")->execute(['SUPA APETI TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['APETAMIN TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['LOPERAMIDE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['PEN V']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['BISACODYL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['MULTIVITE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['FOLIC ACID']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['BCO']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['CITRO C']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['ORS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['MARTINSS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['NO 10']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['OSTEOCARE TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['OSTEOCARE SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['BABYVITE SYRUP S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['BABYVITE SYRUP B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['KIDIVITE SYRUP S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['KIDIVITE SYRUP B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['GLUCOSE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['APETATRUST SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['CYFEN SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['GUDAPEST SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 39.00 WHERE `item` = ?")->execute(['GML APETI SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 37.00 WHERE `item` = ?")->execute(['HEPTOLIF SYRUP B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['HEPTOLIF SYRUP S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ABYVITA SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 27.00 WHERE `item` = ?")->execute(['LEENA SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 65.00 WHERE `item` = ?")->execute(['APETAMIN SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['ROBB INHALER']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['KLIRE INHALER']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['JET 2 INHALER']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['FOLIVITE SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['3FER SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['DUROL S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['DUROL B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['DEXORANGE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['FOLIGROW SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['FOLIGROW PLUS SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['CCORORANGE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['HAEMOFORTE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['BECOATIN SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['BX SYRUP S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 27.00 WHERE `item` = ?")->execute(['BX SYRUP B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['VIGORIX FORTE SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['VIGORIX FORTE CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['ABYVITA CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ABYVITA SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 39.00 WHERE `item` = ?")->execute(['JARIFAN 2 SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ESKARON SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 54.00 WHERE `item` = ?")->execute(['HAEM UP SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['FERROFIX SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['NEXCOFER SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 38.00 WHERE `item` = ?")->execute(['NEOFERON SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 67.00 WHERE `item` = ?")->execute(['ZINCOFER SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['VIROL SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 115.00 WHERE `item` = ?")->execute(['FEROGLOBIN SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 42.00 WHERE `item` = ?")->execute(['CITY BLOOD TONIC']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['LUMETRUST SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['MALAR 2 SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['CARTEF SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['LUFART SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['LONART SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['QUININE SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ARFAN SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 24.00 WHERE `item` = ?")->execute(['GOLDY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['CALCIUM B12 SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 69.00 WHERE `item` = ?")->execute(['TRES-ORIX B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['TRES ORIX S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['CIROTAMIN SYUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['ZINCOVIT SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['ENERVII']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 125.00 WHERE `item` = ?")->execute(['CYPRODINE SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 125.00 WHERE `item` = ?")->execute(['CYPRODINE CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['ZINCOVIT CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['CORORANGE CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['FOLIGROW CAPS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['NEXCOFER CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['GACET 1G']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['GR PARA 500MG SUPP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.50 WHERE `item` = ?")->execute(['GACET 125 SUPP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.50 WHERE `item` = ?")->execute(['GACET 250 SUPP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['DICLOFENAC SUPP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['DOMI 30']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['DOMI 10']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['MALAR 2 TABS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['LUFART DS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['CARTEF 20 120 TABS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['LONART 20/120 TABS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['LUFART 20/120 TABS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['CARTEF DS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['VEGATEM TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['CENART FORTE TABS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['SHALARTEM TABS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ARFAN TABS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['POLYFER CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['POLYFER 150MLS SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 26.00 WHERE `item` = ?")->execute(['POLYER 200MLS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['MAGNAVITE CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['MAGNAVITE SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['SEPTRIN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['PARA LOCAL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['BRUFFEN SKYBRU']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['RONFIT FORTE CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['PELADOL EXTRA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['MALARIA TEST']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ESKYPAN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['LADINAS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['TYPHOID TEST']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['ZUBES LOZENGES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['PREGNANCY TEST']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['BECOATIN TABLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['CIROTAMIN TABLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['APETATRUST TABLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['GYPRONE PLUS TABLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['LEENA TABLETS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 53.00 WHERE `item` = ?")->execute(['MILK OF MAGNESIA B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['MILK OF MAAGNESIA S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 100.00 WHERE `item` = ?")->execute(['IMPRESSOR CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 95.00 WHERE `item` = ?")->execute(['IMPRESSOR OIL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['AMINO KLIRE SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ODYMIN SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['YOGIFER SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['BIOGLOBIN S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['BIOGLOBIN B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ESKARON CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['KOFOF FAMILY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['LETAPLEX B']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['AYTRONS MULTIVITAMINS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 112.00 WHERE `item` = ?")->execute(['FEROGLOBIN CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.50 WHERE `item` = ?")->execute(['PLASTER STRIP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 16.00 WHERE `item` = ?")->execute(['CETAPOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['PARAMED']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 16.00 WHERE `item` = ?")->execute(['E-PANOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['LETAMOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['SKY PARA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ENAFEN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['SKYBRU SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['EMGIPROFEN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['CHILDCARE LETAFEN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['RIDDLES PARACETAMOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['AMCOF JUNIOR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['AMCOF INFANT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['RIDDLES JUNIOR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['TEEDAR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['EFPAC JUNIOR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 16.00 WHERE `item` = ?")->execute(['ZUDREX SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['SALOCOLD SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['BASECOLD SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['COLDRILIF SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 38.00 WHERE `item` = ?")->execute(['CONGESTYL SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['PROCOLD SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 21.00 WHERE `item` = ?")->execute(['FLEMEX SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['MENTHOX JUNIOR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ZUBES JUNIOR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['STOPKOF JUNIOR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['STOPKOF INFANT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['MALIN JUNIOR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['MALIN BABY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['KOFOF BABY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['KOFFEX JUNIOR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['SAMALIN JUNIOR PLAIN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['SAMALIN JUNIOR NON DROWSY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['LUEX CHESTY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['LUEX BABY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['MUCOLEX JUNIOR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['BELLS PARACETAMOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['KOFOF CHILD']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['SALBUTALIN SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['SEVEN SEAS COD LIVER OIL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 112.00 WHERE `item` = ?")->execute(['CALPOL 2+ SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['BELS COD LIVER OIL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['CETRIZAN SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['HISTAZINE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['PROMETHAZINE SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['PROMECINE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ASCORYL PLUS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['ASCORYL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['BELL’S VIT C']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['LETAVIT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['CHILDCARE ASCORBIN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['LABFLU']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 26.00 WHERE `item` = ?")->execute(['ANTIE MARY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['BONNISAN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['SALO-C']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['ESKADOL NITE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['CONGESTYL TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ZUDREX TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['SALOCOLD TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['RONFIT COLD TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['FLUREST']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['SAMALIN LOZENGES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['MALIN LOZENGES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['LEXOFEN CAPLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ASNAC 75']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ASNAC 100']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['LOFNAC/DICNAC 100 TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['APC']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ZULU 100']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 14.00 WHERE `item` = ?")->execute(['ZULU MR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ZULU EXTRA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['GOFEX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['BRUPREX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['NAKLOFEN DUO']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['BRUFFEN UK']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['PAINGAY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['FENBASE EXTRA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['DIPEX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['DOLO PLUS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['DOLO TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['ZULU PLUS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['GEBEDOL PLUS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['GEBEDOL EXTRA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['GEBEDOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['GEBEDOL FORTE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['PARAFENAC']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['PARAFENAC EXTRA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['COLDRILIF CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['PROCOLD TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['CETRIZAN TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['IBUCAP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 26.00 WHERE `item` = ?")->execute(['FISHERMAN’S FRIEND']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['BABYVITE DROPS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['CORORANGE DROPS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['ZINCOVITE DROPS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['KIDIVITE DROPS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['VALUPAK COD LIVER OIL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['VITAMIN BCO POROSURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['VITAMIN BCO ACCORD']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 48.00 WHERE `item` = ?")->execute(['FOLIC ACID 90’S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['FOLIC ACID 30’S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['FOLIC ACID 28’S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 37.00 WHERE `item` = ?")->execute(['VITAFOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['KOJACK P']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['KOJACK F']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['CHOCHO CREAM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['RONFIT OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['EPIDERM B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['EPIDERM S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 37.00 WHERE `item` = ?")->execute(['SURFAZ']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['DIPROSON CREAM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['CANDIDERM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['TETRACYCLINE OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['MYCOLEX CREAM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['MYCOLEX 3 CREAM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['ESKYZOLE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['MERCY OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['FUNBACT A B/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['FUNBACT A S/S']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['KETAZOLE CREAM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['PEN V OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['BADRUFF']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['DERMIRON PLUS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['LAVINA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 24.00 WHERE `item` = ?")->execute(['MAJOR NASAL DROP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['SANA NASAL DROP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['CHLOR EAR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['GENTA K']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['RAMICOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['EXEVIN ADULT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['OLIVE OIL EAR DROP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 27.00 WHERE `item` = ?")->execute(['SECLEAR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['CIPROLEX EAR/EYE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 95.00 WHERE `item` = ?")->execute(['PILEX TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['PILEX OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['OMEGA OIL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['DREZ POWDER']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['DREZ SOLUTION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['DREZ OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['DEXONE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['COMBACT A']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['BELLS OLIVE OIL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['MERCY SOAP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['CHOCHO SOAP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['CHLORAMPHENICOL OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['BORGES OLIVE OIL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 56.00 WHERE `item` = ?")->execute(['NEO-HYCOLEX EAR/EYES/NOSE DROP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 49.00 WHERE `item` = ?")->execute(['DEEP HEAT OINTMENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['KWICK ACTION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['PAIN OFF']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['DYNEWELL TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['CHLORAMPHENICOL CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['LETACAM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['RAPINOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['YODI']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['AMPICILLIN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['FLAGYL TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['AMOXYL CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['LETAVIN 125']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['LETAVIN 500']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['TETRACYCLINE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['SKYCID OMEPRAZOLE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['ASMANOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['ASMADRIN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 3.00 WHERE `item` = ?")->execute(['RHIZIN TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 1.00 WHERE `item` = ?")->execute(['M AND B 760']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['FLUCLOXACILLIN CAPSULES 250MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['DOXYCYCLINE CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['SALBUTAMOL TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['FIESTA GEL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['FIESTA CONDOM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['LEVON 2 GEL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['INDOCID']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['AMCICLOX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['STREPTOL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 70.00 WHERE `item` = ?")->execute(['VERMOX SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 47.00 WHERE `item` = ?")->execute(['ZENTEL SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 130.00 WHERE `item` = ?")->execute(['M2 TONE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['WORMPLEX TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['WORMPLEX SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 8.00 WHERE `item` = ?")->execute(['TANZOL SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['NESBEN SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['LETAMOX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['VERMOX TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['TRUSTZOLE SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['TRUSTZOLE TABLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['TANZOL TABLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['WORMPLEX TABLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['ZENTEL TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['NESBEN TABLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['DUREX FEATHER']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['DUREX FEELS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['DUREX EXTRA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 9.00 WHERE `item` = ?")->execute(['CONTRA 72']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['LEVON 2']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['LYDIA POSTPILL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['LYDIA DAILY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['FLUCONAZOLE VEGA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['STAGYL TABLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['FLUCONAZOLE TEVA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 17.00 WHERE `item` = ?")->execute(['MYCOSTAT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 6.00 WHERE `item` = ?")->execute(['SECURE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['VAGINAX 100']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['KLOVINAL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['CANALEX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 65.00 WHERE `item` = ?")->execute(['GYNO MYCOLEX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 54.00 WHERE `item` = ?")->execute(['DRAGON SPRAY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 70.00 WHERE `item` = ?")->execute(['IMAX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['KISS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['EBONY ORIGINAL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['EBONY PLUS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['REDSUN CAPSULES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['REDSUN JELLY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['DRAGON LOZENGES']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['DRAGON TABLET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['BASEBOOM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['KISS JELLY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['FLAMES CONDOM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['GOLD CIRCLE CONDOM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['BK-1']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['AMLODIPINE 10MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['AMLODIPINE 5MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 14.00 WHERE `item` = ?")->execute(['LOSARTAN 50 MG TEVA PER STRIP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 14.00 WHERE `item` = ?")->execute(['LOSARTAN 100M TEVA PER STRIP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['LOSARTAN 50 MG CRESCENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 11.00 WHERE `item` = ?")->execute(['LOSARTAN 100 MG CRESCENT']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['O-FORMIN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['NIFECARD XL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['NIFEMED XL']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['ATORVASTATIN 20 MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['ATORVASTATIN 40 MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 8.00 WHERE `item` = ?")->execute(['BENDRO 2.5MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 11.00 WHERE `item` = ?")->execute(['BENDRO 5MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['LISINOVA 10MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['NIFEDOSE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['ENACIN- C']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['DACILLIN']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['ACYCLOVIR 200 MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 29.00 WHERE `item` = ?")->execute(['ACYCLOVIR 400MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 55.00 WHERE `item` = ?")->execute(['SKYCLAV 1G']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 50.00 WHERE `item` = ?")->execute(['SKYXLAV 625MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['GRMOX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['ZOLEXOV']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 31.00 WHERE `item` = ?")->execute(['LEOAB 500MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 70.00 WHERE `item` = ?")->execute(['CIPROLEX TZ']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['CIPROLEX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['AMOKSIKLAV 625MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['METRO F TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['ZYMAX TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 42.00 WHERE `item` = ?")->execute(['ENAFIX 200 TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['ENAFIX 200 SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 53.00 WHERE `item` = ?")->execute(['FOXITIL 500MG TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['OMEXET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['AZILEX SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['OXYNIC 457 SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['OXYNIC 228.5MG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 35.00 WHERE `item` = ?")->execute(['SKYCLAV457MG SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['FLAGYL 21’S TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['NOSPA']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['AMOKSIKLAV 457 SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 27.00 WHERE `item` = ?")->execute(['FLUXACIN SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 60.00 WHERE `item` = ?")->execute(['SOLUBLE VIT C']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 40.00 WHERE `item` = ?")->execute(['VITACARE PLUS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 23.00 WHERE `item` = ?")->execute(['AMOXICILLIN SUSPENSIONLUEX']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['AMOXICILLIN SUSP LETAP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['FLAGYL SUSPENSION LETAP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['X’ZOLE SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 45.00 WHERE `item` = ?")->execute(['METRO F SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 15.00 WHERE `item` = ?")->execute(['FUMET']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['CO-TRIMOXAZOLE LETAP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['CO-TRIMOXAZOLE MPG']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 27.00 WHERE `item` = ?")->execute(['SALO FULVIN SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 33.00 WHERE `item` = ?")->execute(['KEFFROX SUSPENSION']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['SHALCIP TZ']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 0.00 WHERE `item` = ?")->execute(['SHALCIP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 7.00 WHERE `item` = ?")->execute(['COMIT 50 TAB']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 5.00 WHERE `item` = ?")->execute(['COMIT 100 JELLY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 2.00 WHERE `item` = ?")->execute(['PREDNISOLONE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 4.00 WHERE `item` = ?")->execute(['GAUZE BANDAGE']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 10.00 WHERE `item` = ?")->execute(['CREPE BANDAGE 4’’']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['CREPE BANDAGE 6’’']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 8.00 WHERE `item` = ?")->execute(['CREPE BANDAGE 3’’']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['PLASTER ROLL 2’’']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 25.00 WHERE `item` = ?")->execute(['PLASTER ROLL 4’’']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['PLASTER ROLL 6’’']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['VALUPAK MULTIVITAMINS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 30.00 WHERE `item` = ?")->execute(['YOGIFER SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 28.00 WHERE `item` = ?")->execute(['ABYTONE SYR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 65.00 WHERE `item` = ?")->execute(['ODYYNE SYRUP']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 14.00 WHERE `item` = ?")->execute(['ZULU MR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 65.00 WHERE `item` = ?")->execute(['ODYNE CAPS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 13.00 WHERE `item` = ?")->execute(['RHIZIN SYR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 12.00 WHERE `item` = ?")->execute(['KLIRE TABLETS']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 18.00 WHERE `item` = ?")->execute(['CETAPOL PM']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['DIPHEX BABY']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 20.00 WHERE `item` = ?")->execute(['DIPHEX JUNIOR']); $count++;
        $pdo->prepare("UPDATE `inventory` SET `unit_price` = 22.00 WHERE `item` = ?")->execute(['KELCUF JNR']); $count++;
        echo "<p>✅ $count items updated.</p>";
    } catch (PDOException $e) {
        echo "<p>❌ Error: " . htmlspecialchars($e->getMessage()) . "</p>";
    }
}
echo "<hr><p><strong>Done! Delete this file now.</strong></p>";
?>